### ISSUE TITLE
Why can't I copy?

### ISSUE THREAD

**Issue by GitStonic** [valeth/discord-rpc-client.rs#7]
Yeah, basically I was wondering why can't I use `.clone()` function on the `Client` struct? Is there a main reason you didn't implement the Copy or Clone trait on it?

**Comment by valeth** [comment]
Mainly just did it like this because of simplicity, and not having to wrap the inner connection manager in an `Arc<Mutex<ConnectionManager>>`.

**Comment by valeth** [comment]
Fixed with 84de596 and crate version 0.3.0
